_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "3":
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.8
            "6": 4.50.0
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
